import { Flux } from "../src";

const flux = new Flux({
  url: "lux://10.0.0.176:6379",
  name: "writer",
});

flux.expose("draft", async (payload: any) => {
  const { topic, findings, style } = payload;
  console.log(`\n  drafting ${style || "report"} on "${topic}"...`);
  console.log(`  using ${findings.length} findings`);

  await sleep(600);

  const bullets = findings.map((f: string) => `  - ${f}`).join("\n");
  const report = [
    `# ${topic}`,
    "",
    `## Key Findings`,
    "",
    bullets,
    "",
    `## Analysis`,
    "",
    `Based on ${findings.length} data points, the evidence suggests significant`,
    `momentum in ${topic.toLowerCase()}. The data paints a clear picture of`,
    `accelerating change with broad implications.`,
    "",
    `---`,
    `Generated by writer peer via Flux`,
  ].join("\n");

  console.log(`  draft complete (${report.length} chars)`);
  return report;
});

flux.expose("summarize", async (payload: any) => {
  const { text, maxLength } = payload;
  console.log(`\n  summarizing ${text.length} chars...`);
  await sleep(400);

  const lines = text.split("\n").filter((l: string) => l.startsWith("  - "));
  const summary = lines.length > 0
    ? `${lines.length} key findings identified. ` + lines.slice(0, 2).map((l: string) => l.trim().replace("- ", "")).join(". ") + "."
    : text.slice(0, maxLength || 200);

  console.log(`  summary: "${summary.slice(0, 80)}..."`);
  return summary;
});

await flux.start();
await flux.join("demo");

flux.on("peer:joined", (e) => console.log(`  + ${e.peerName} joined`));
flux.on("peer:left", (e) => console.log(`  - ${e.peerName} left`));
flux.on("ctx:updated", (e) => console.log(`  ctx "${e.key}" updated by ${e.peerName}`));

console.log("writer online");
console.log("capabilities: draft, summarize");
console.log("workspace: demo\n");
console.log("waiting for work...");

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}
